version: '3'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '8888:8888'
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: lesson
      DB_PASSWORD: lesson
      DB_DATABASE: lesson

  db:
    image: postgres
    container_name: postgresql
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=lesson
      - POSTGRES_PASSWORD=lesson
      - POSTGRES_DB=lesson

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379:6379'
