export const users =
   [
      {
         "_id": "63c81b89cd97bd30113783f1",
         "isActive": true,
         "balance": "$2,484.14",
         "picture": "http://placehold.it/32x32",
         "age": 33,
         "eyeColor": "brown",
         "name": "Morin Swanson",
         "gender": "male",
         "company": "GOGOL",
         "email": "morinswanson@gogol.com",
         "phone": "+1 (848) 477-2531",
         "address": "817 Schenck Court, Accoville, Florida, 265"
      },
      {
         "_id": "63c81b8941f859f4a62ded39",
         "isActive": false,
         "balance": "$2,958.36",
         "picture": "http://placehold.it/32x32",
         "age": 21,
         "eyeColor": "brown",
         "name": "Meghan Bell",
         "gender": "female",
         "company": "INSURITY",
         "email": "meghanbell@insurity.com",
         "phone": "+1 (960) 410-3014",
         "address": "566 Alice Court, Day, American Samoa, 2095"
      },
      {
         "_id": "63c81b893e6ae4d29f080aa2",
         "isActive": true,
         "balance": "$1,757.45",
         "picture": "http://placehold.it/32x32",
         "age": 28,
         "eyeColor": "brown",
         "name": "Montoya Mckay",
         "gender": "male",
         "company": "BIOTICA",
         "email": "montoyamckay@biotica.com",
         "phone": "+1 (967) 435-2156",
         "address": "764 Front Street, Dubois, California, 2649"
      },
      {
         "_id": "63c81b899b0ecdf5592cf80d",
         "isActive": false,
         "balance": "$2,993.15",
         "picture": "http://placehold.it/32x32",
         "age": 36,
         "eyeColor": "brown",
         "name": "Betsy Hensley",
         "gender": "female",
         "company": "GYNKO",
         "email": "betsyhensley@gynko.com",
         "phone": "+1 (877) 410-3847",
         "address": "901 Knickerbocker Avenue, Draper, Maine, 3676"
      },
      {
         "_id": "63c81b89b7d4e685df9be2cb",
         "isActive": true,
         "balance": "$3,818.81",
         "picture": "http://placehold.it/32x32",
         "age": 33,
         "eyeColor": "green",
         "name": "Deleon Carlson",
         "gender": "male",
         "company": "COSMOSIS",
         "email": "deleoncarlson@cosmosis.com",
         "phone": "+1 (965) 405-3065",
         "address": "714 Cozine Avenue, Martinez, Wyoming, 8975"
      },
      {
         "_id": "63c81b895fc9233b740c23ce",
         "isActive": true,
         "balance": "$1,385.75",
         "picture": "http://placehold.it/32x32",
         "age": 25,
         "eyeColor": "brown",
         "name": "Celeste Vazquez",
         "gender": "female",
         "company": "DELPHIDE",
         "email": "celestevazquez@delphide.com",
         "phone": "+1 (954) 598-2985",
         "address": "658 Bleecker Street, Allison, Vermont, 8246"
      },
      {
         "_id": "63c81b892bcfbf7ce57522cd",
         "isActive": false,
         "balance": "$3,003.84",
         "picture": "http://placehold.it/32x32",
         "age": 30,
         "eyeColor": "green",
         "name": "Justice Dixon",
         "gender": "male",
         "company": "AFFLUEX",
         "email": "justicedixon@affluex.com",
         "phone": "+1 (865) 534-2442",
         "address": "711 Crown Street, Flintville, Guam, 6567"
      }
   ]